version: '3.8'

services:
  servicea:
    image: servicea:latest
    build:
      context: .
      dockerfile: ServiceA/Dockerfile

  serviceb_1:
    image: serviceb:latest
    build:
      context: .
      dockerfile: ServiceB/Dockerfile

  serviceb_2:
    image: serviceb:latest
    build:
      context: .
      dockerfile: ServiceB/Dockerfile

  servicec_1:
    image: servicec:latest
    build:
      context: .
      dockerfile: ServiceC/Dockerfile

  servicec_2:
    image: servicec:latest
    build:
      context: .
      dockerfile: ServiceC/Dockerfile

  servicegateway:
    image: servicegateway:latest
    build:
      context: .
      dockerfile: ServiceGateway/Dockerfile

  sqlserver:
    container_name: sqlserver

  adminer:
    container_name: adminer

  rabbitmq:
    container_name: rabbitmq

  redis:
    container_name: redis
    
  redis-commander:
    container_name: redis-commander

  consul:
    container_name: consul

  prometheus:
    container_name: prometheus

  grafana:
    container_name: grafana

  elasticsearch:
    container_name: elasticsearch

  logstash:
    container_name: logstash

  kibana:
    container_name: kibana