version: '3.8'

services:
  servicea:
    image: servicea:latest
    container_name: servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ServiceADB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:UserName=guest
      - RabbitMQ:Password=guest
      - Consul:Url=http://consul:8500
      - HealthCheck:Address=servicea
      - HealthCheck:Port=8001
    ports:
      - 8001:8001
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
      - consul

  serviceb_1:
    image: serviceb:latest
    container_name: serviceb_1
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8002
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ServiceBDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:UserName=guest
      - RabbitMQ:Password=guest
      - Redis:ConnectionString=redis:6379
      - Consul:Url=http://consul:8500
      - HealthCheck:Address=serviceb_1
      - HealthCheck:Port=8002
      - Service:ID=ServiceB_1
    ports:
      - 8002:8002
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
      - consul

  serviceb_2:
    image: serviceb:latest
    container_name: serviceb_2
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8002
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ServiceBDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:UserName=guest
      - RabbitMQ:Password=guest
      - Redis:ConnectionString=redis:6379
      - Consul:Url=http://consul:8500
      - HealthCheck:Address=serviceb_2
      - HealthCheck:Port=8002
      - Service:ID=ServiceB_2
    ports:
      - 8012:8002
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
      - consul

  servicec_1:
    image: servicec:latest
    container_name: servicec_1
    build:
      context: .
      dockerfile: ServiceC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8003
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ServiceCDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:UserName=guest
      - RabbitMQ:Password=guest
      - Consul:Url=http://consul:8500
      - ShortCodeConfig:Prefix=D1
      - HealthCheck:Address=servicec_1
      - HealthCheck:Port=8003
      - Service:ID=ServiceC_1
    ports:
      - 8003:8003
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
      - consul    

  servicec_2:
    image: servicec:latest
    container_name: servicec_2
    build:
      context: .
      dockerfile: ServiceC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8003
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ServiceCDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:UserName=guest
      - RabbitMQ:Password=guest
      - Consul:Url=http://consul:8500
      - ShortCodeConfig:Prefix=D2
      - HealthCheck:Address=servicec_2
      - HealthCheck:Port=8003
      - Service:ID=ServiceC_2
    ports:
      - 8013:8003
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
      - consul    

  servicegateway:
    image: servicegateway:latest
    container_name: servicegateway
    build:
      context: .
      dockerfile: ServiceGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8010
      - Consul:Url=http://consul:8500
      - HealthCheck:Address=servicegateway
      - HealthCheck:Port=8010
    ports:
      - 8010:8010
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - 433:1433

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - sqlserver

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6380:8081
    depends_on:
      - redis

  consul:
    image: hashicorp/consul:1.15.4
    container_name: consul
    ports:
      - 8500:8500

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "2000:3000"
    depends_on:
      - prometheus