global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'servicea'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['servicea:8001']

  - job_name: 'serviceb'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['serviceb:8002']

  - job_name: 'servicec'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['servicec:8003']
